input {
  file {
    path => "/var/log/app/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  date {
    match => ["asctime", "yyyy-MM-dd HH:mm:ss,SSS"]
    target => "@timestamp"
    timezone => "Asia/Kolkata"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "signlanguage-logs"
  }
  stdout {
    codec => rubydebug
  }
}