pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE_FRONTEND = "shaikirfan273/signlang-frontend"
        DOCKER_IMAGE_BACKEND = "shaikirfan273/signlang-backend"
        SERVER_IP = "192.168.0.117"
    }
    
    stages {
        stage('Configure Docker Permissions') {
            steps {
                sh '''
                echo "Configuring Docker permissions..."
                sudo usermod -aG docker jenkins
                sudo systemctl restart docker
                '''
            }
        }
        
        stage('Setup Python') {
            steps {
                sh '''
                sudo apt-get update
                sudo apt-get install -y python3-full python3-pip python3-venv
                '''
            }
        }
        
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/SHAIK-MOHAMMAD-IRFAN27/REAL_TIME_SIGN_LANGUAGE_CHATBOT_END2END.git'
            }
        }
        
        stage(' Frontend environment') {
            steps {
                dir('SPE_SignLang/frontend') {
                    sh '''
                    python3 -m venv frontend_env
                    . frontend_env/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }
        
        // stage(' Backend environment') {
        //     steps {
        //         dir('SPE_SignLang/backend') {
        //             sh '''
        //             python3 -m venv myenv
        //             . myenv/bin/activate
        //             pip install -r requirements.txt
        //             '''
        //         }
        //     }
        // }
        
        // stage('Containerize Applications') {
        //     steps {
        //         script {
        //             sh '''
        //             echo "Building Frontend Docker Image frontend..."
        //             sudo docker build -t ${DOCKER_IMAGE_FRONTEND} ./SPE_SignLang/frontend
                    
        //             echo "Building Backend Docker Image backend..."
        //             sudo docker build -t ${DOCKER_IMAGE_BACKEND} ./SPE_SignLang/backend
        //             '''
        //         }
        //     }
        // }
        
        // stage('Push to Docker Hub') {
        //     steps {
        //         withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials',
        //                                         usernameVariable: 'DOCKER_USER',
        //                                         passwordVariable: 'DOCKER_PASS')]) {
        //             sh '''
        //             echo "Logging into Docker Hub..."
        //             echo "${DOCKER_PASS}" | sudo docker login -u "${DOCKER_USER}" --password-stdin
                    
        //             echo "Pushing Frontend Image..."
        //             sudo docker push ${DOCKER_IMAGE_FRONTEND}
                    
        //             echo "Pushing Backend Image..."
        //             sudo docker push ${DOCKER_IMAGE_BACKEND}
        //             '''
        //         }
        //     }
        // }
        
        
        stage('Run docker compose Kubernetes Minikube Playbook') {
            steps {
                sh '''
                echo "Running Docker Compose to bring up app and ELK stack"
                docker-compose up -d --build
                echo "Running Kubernetes Minikube Ansible Playbook"
                ansible-playbook -i hosts.ini playbook.yml
            '''
            }
        }

    }

    post {
        success {
            echo "Pipeline executed successfully! SPE_SignLang application is deployed.."
        }
        failure {
            echo "Pipeline failed! Check the logs for errors..."
        }
    }
} 